server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: shopsphere-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/shopsphere?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: nirajsql@8945
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    com.shopsphere: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours
